default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/sourcery-ai/sourcery
    rev: v1.0.1
    hooks:
      - id: sourcery
        args: [--diff=git diff HEAD, --no-summary]
